# Generated by Django 2.2.16 on 2022-05-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_auto_20220530_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('anon', 'Anonymous User'), ('user', 'Authenticated User'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='user', max_length=9),
        ),
    ]
