# Generated by Django 2.2.16 on 2022-05-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_auto_20220530_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
